export interface PersonnelDataResult {
  PER_CITIZEN_ID: string;
  TYPE_CODE: number;
  TYPE_NAME: string;
  PER_SLIP_ID: string;
  PER_POS_ID: number;
  PRE_CODE: number;
  PRE_NAME: string;
  PER_NAME_TH: string;
  PER_NAME_EN: string;
  PER_MIDDLE_NAME_EN?: string;
  PER_TAX_ID: string;
  PER_PVDF_APP: string;
  PER_PVDF_APP_D: string;
  PER_PVDF_QUIT: string;
  PER_PVDF_QUIT_D: string;
  PER_FUND_TYPE: number;
  PER_SAVE_RATE: number;
  PER_SSO_PAYMENT: number;
  PER_FUND_TEACHER: number;
  PER_FUND_ASSTEACHER: number;
  PER_SSO_ID: string;
  PER_PASSPORT_NO: string;
  PER_PASSPORT_START_D: string;
  PER_PASSPORT_EXPIRE_D: string;
  POSC_NAME: string;
  PER_FAC_C: number;
  FAC_NAME: string;
  PER_SALARY: number;
  PER_HOLD_SALARY: number;
  CREATED_DATE: string;
  CREATED_BY: string;
  UPDATED_DATE: string;
  UPDATED_BY: string;
  FULL_NAME_TH?: string;
  FUND_NAME?: string;
}

export interface PersonnelInsertInput {
  perCitizenId: string;
  typeCode: number | null;
  typeName: string;
  perSlipId: string;
  perPosId: number | null;
  preCode: number | null;
  preName: string;
  perNameTh: string;
  perNameEn: string;
  perFirstNameEn: string;
  perMiddleNameEn: string;
  perLastNameEn: string;
  perTaxId: string;
  perPvdfApp: string;
  perPvdfAppD: string | null;
  perPvdfQuit: string;
  perPvdfQuitD: string | null;
  perFundType: number | null;
  perSaveRate: number | null;
  perSsoPayment: number | null;
  perFundTeacher: number | null;
  perFundAssteacher: number | null;
  perSsoId: string;
  perPassportNo: string;
  perPassportStartD: string | null;
  perPassportExpireD: string | null;
  poscName: string;
  perFacC: number | null;
  facName: string;
  perSalary: number | null;
  perHoldSalary: number | null;
}
